### ISSUE TITLE
Postman Erro

### ISSUE THREAD

**Issue by Raphacorrea** [cami-la/academia-digital#19]
Olá Camila! Tudo bem? 
Não consigo passar informações no Postman como executado na aula.
Em criar aluno quando eu passo as informações em json no body o meu retorno é que a mídia não é compatível.
Tem como me ajudar?

**Comment by cami-la** [comment]
Oi, @Raphacorrea. Tudo bem sim e por aí? (:
Manda o print aqui!

**Comment by Raphacorrea** [comment]
Olha eu estou a uma semana tentando resolver isso

**Comment by Raphacorrea** [comment]
<img width="1315" alt="Screen Shot 2022-08-17 at 10 46 41" src="https://user-images.githubusercontent.com/97764348/185275361-bfec3996-3436-4045-a45b-7fe6e23dd01f.png">

**Comment by cami-la** [comment]
Tenta o seguinte:

![2022-08-18_08-06](https://user-images.githubusercontent.com/64323124/185380669-2e9aa08a-74a4-43d3-b9f6-e79ce43e2818.png)

**Comment by Raphacorrea** [comment]
Em cima nao tem a opção mas embaixo mostra já configurado com json.
Tem outra maneira de adicionar estes dados pelo DBeaver por exemplo, sem o uso do postman?
<img width="1217" alt="Screen Shot 2022-08-18 at 09 45 07" src="https://user-images.githubusercontent.com/97764348/185397984-f69102f5-d91a-4d67-8ac6-f7c0bc33ed7b.png">

**Comment by cami-la** [comment]
> Em cima nao tem a opção mas embaixo mostra já configurado com json. Tem outra maneira de adicionar estes dados pelo DBeaver por exemplo, sem o uso do postman? <img alt="Screen Shot 2022-08-18 at 09 45 07" width="1217" src="https://user-images.githubusercontent.com/97764348/185397984-f69102f5-d91a-4d67-8ac6-f7c0bc33ed7b.png">

E

**Comment by cami-la** [comment]
Então, @Raphacorrea. O Postman é pra que teste das requisições para nossa API. Se você "chumbar" os dados no DBeaver, você não consegue testar o método POST de inserir dados no servidor através da API. :(

Vou te dar a collection que estou usando no meu Postamn e você importa para seu Postam aí.
Pega aqui nesse comentário de outra issue: https://github.com/cami-la/academia-digital/issues/10#issuecomment-1149666329

1. Você vai fazer o download do zip acima e descompactar;
2. No Postam, ao lado de "My Workspace" tem um botão chamando "Import", aí você importa essa collecion utiizando a opção "Upload Files";
3. Faz a adaptações necessárias. Por exemplo, pelo que eu vvi, a porta que estou usando é a 8081 e você a 8080...

Enfim, caso não dê certo, talvez tenha algum erro no código-fonte da sua API.
No último caso, faz um clone do meu projeto e tenta rodar aí na sua máquina e vê se dá certo.
