### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by dan-araujo** [cami-la/academia-digital#30]
Olá, quando eu tento rodar o código e fazer uma requisição para criar um novo aluno no Postman, aparece a seguinte mensagem:
JSON parse error: Text '07/07/2000' could not be parsed at index 10]

Eu tentei de várias formas descobrir porque da esses erros e até colocando essas anotações acima da variável dataNascimento pra ver se a serialização e deserialização funcionariam, mas o erro persiste:
```
@Column(name = "data_nascimento")
@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy")
@JsonDeserialize(using = LocalDateDeserializer.class)
@JsonSerialize(using = LocalDateSerializer.class)
private LocalDate dataNascimento
```

Classes diretamente sendo importadas do pacote infra.jackson
Você poderia me ajudar?

**Comment by cami-la** [comment]
Oi, @dan-araujo. Tudo bem?

Então, você está importando as classes do pacote infra corretamente?
Faz o seguinte, clona o meu projeto para sua máquina e tenta rodar o código para ver se apresenta o mesmo erro.
