### ISSUE TITLE
Onde vejo as aulas?

### ISSUE THREAD

**Issue by AgnoDev** [cami-la/academia-digital#34]
Boa noite. Sou aluno DIO GLOBAL e gostaria de assistir as suas aulas referentes a esse projeto. Você poderia me indicar onde encontro? 
Grato.

**Comment by cami-la** [comment]
Aqui tem todas as aulas: https://www.dio.me/dev-week/ifood/ifood-developer

**Comment by AgnoDev** [comment]
thanks!
