### ISSUE TITLE
push no git

### ISSUE THREAD

**Issue by AgnoDev** [cami-la/academia-digital#35]
Boa noite. Clonei o projeto e não estou conseguindo comitar nem subir para o meu repositorio.

![image](https://user-images.githubusercontent.com/125305556/234464921-bd1c6b2b-f5e1-4bda-a76e-c5153fc552cb.png)

vc pode me ajudar?

**Comment by cami-la** [comment]
Oi, amigo. Tudo certo?
Você está tentando fazer um push para o meu repositório. Você precisa fazer para o seu.

**Comment by AgnoDev** [comment]
eu entendi essa parte, mas não sei como trocar

já criei meu repositorio https://github.com/AgnoDev/academia-api.git
mas não cosigo colocar ele lá 
help me

**Comment by cami-la** [comment]
Acredito que não dá para trocar, viu? 
Precisa iniciar outro projeto. Mas você conseguiu, né?

**Comment by AgnoDev** [comment]
sim, consegui. mas não consigo subir no meu repositorio. mesmo assim, obrigado pela atenção.

**Comment by cami-la** [comment]
Quer explicar um pouco mais da sua dúvida? Mandar um print do erro?

No YouTube tenho 2 vídeos que mostra 2 formas de fazer o push no GitHub:

1. Access Token: https://www.youtube.com/watch?v=wcIm916zk9w&list=PL8kiySPPUO-whdpuxIWVcfUQqYfjeaY_I&ab_channel=CamilaCavalcante
2. SSH Key: https://www.youtube.com/watch?v=xeIErHwL53Q&list=PL8kiySPPUO-whdpuxIWVcfUQqYfjeaY_I&index=2&ab_channel=CamilaCavalcante
