### ISSUE TITLE
Postman

### ISSUE THREAD

**Issue by iandealmeida** [cami-la/academia-digital#8]
Oi Camila, tudo bem?

Olha, adoro as suas aulas! Acho vc e Felipe Aguiar os melhores instrutores da DIO!

Agora eu empaquei numa dificuldade no seu video "CROODs Parte 1", da aula "Conhecendo Spring Data JPA na prática com Java".

Já no final do video você mostra que preparou um Postman com os métodos configurados para popular as tabelas do banco de dados.

O problema é que essa ferramenta não foi apresentada e não entendi se a gente deve usar ela ou não.

O que preciso fazer?

- Configurar nosso próprio Postman com os métodos (como)?
- Conectar com a sua coleção no Postman (não consegui encontrar)?
- Seguir sem usar o Postman?

Agradeço se puder esclarecer.

**Comment by iandealmeida** [comment]
Consegui resolver, Camila!

Vi que o postman não é difícil de configurar.. é só criar sua conta e instalar o Desktop Agent e criar os métodos do jeito que vi na tela da aula.

**Comment by cami-la** [comment]
Top!! Parabéns.
Qualquer dúvida, fico à disposição! (:
